### ISSUE TITLE
Doesn't show in xplane 11

### ISSUE THREAD

**Issue by ehjort1891** [bastibe/MiniHUD#1]
I have xplane 11 and 12.  In xplane 12 the plugin works as instructed.  Xplane 11 doesn't show anything, but I can see in the keyboard commands and joystick commands the plugin and I can assign it to buttons.  But the buttons don't call up the hud.   For some reason nothing is drawing in xplane 11.

**Comment by bastibe** [comment]
Thank you for opening the issue here on Github.

I've set up a probable fix in the most recent [instrumentpanel.lua](https://github.com/bastibe/MiniHUD/blob/main/data/modules/Custom%20Module/instrumentpanel.lua). The relevant changes are replacing 

```lua
local flapsProp = globalPropertyf("sim/cockpit2/controls/flap_handle_request_ratio")
```

with

```lua
if sasl.getXPVersion() >= 12 then
    local flapsProp = globalPropertyf("sim/cockpit2/controls/flap_handle_request_ratio")
else
    local flapsProp = globalPropertyf("sim/cockpit2/controls/flap_ratio")
end
```

Could you check if this change fixes your issue?

**Comment by ehjort1891** [comment]
Your fix does work in xplane 11.  I do have to check, that the change then doesn't break for xplane 12.

**Comment by bastibe** [comment]
Wonderful! Then I'm closing this issue as completed. Feel free to reopen it, or open a new issue, if the problem persists.
